language: node_js
node_js:
- '6'
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
 - npm build
 - npm test
#before_deploy:
# - git config --global user.email "builds@travis-ci.com"
# - git config --global user.name "Travis CI"
# - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
# - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#    secure: LifWcMvVdfecAE8MwECByqgoJZzjzlbO+0TedFZZ/zP+llfE024QAWluSpL6VrZTvqiAgPUj1M7H2YhxIGfoecnBZSHR+65BMDABFkQ/5Q+yH12iRDLK9bvjr+ToXSe7ia/MAtr08Ma9Z4yCNIOrnb003Liupq/NgNWJL+KQeQk=
#  file:
#    - dist/indexedDBmock.js
#    - dist/indexedDBmock.min.js
#  on:
#    tag: false
#    all_branches: true

#branches:
#  except:
#    - /^*-v[0-9]/